### PR TITLE
Compatible with GNOME Shell 3.14.4

### PR DESCRIPTION
**Pull request by rozzin**
Seems to work perfectly fine with the build in Debian Jessie, anyway.

### CODE REVIEW

**Comment by HarlemSquirrel** [comment]
Sorry, but for some reason I never got an email about this.

**Review by HarlemSquirrel — CHANGES_REQUESTED** [review]
Perhaps we can just make this "3.14"? Do you have a reason to believe it won't work on 3.14.0-3?

**Comment by rozzin** [comment]
On 03/27/2018 06:49 PM, Kevin McCormack wrote:
> *@HarlemSquirrel* requested changes on this pull request.
> 
> Perhaps we can just make this "3.14"? Do you have a reason to believe it won't work on 3.14.0-3?
No idea--I can't really test 3.14.0 at this point.

And even 3.14.4 is ancient at this point--and obsoleted in Debian because
Debian 9.0 (stretch) was released on 2017-06-17 (so normal support for
jessie actually will be ending soon, though the LTS project
will take it out to 2020 <https://wiki.debian.org/LTS>).

I guess there's not really much point in being overly conservative on this,
because the worst that can happen is that someone running an old gnome-shell
and wanting to use this extension finds that it actually _doesn't_ work--right?

Not sure where gnome-shell 3.14.0-3 would be found; Ubuntu's last two LTS releases,
Trusty/14.04 and Xenial/16.04, have had gnome-shell 3.10.4 and 3.18.4, respectively.

Maybe Red Hat....

**Comment by HarlemSquirrel** [comment]
@rozzin OK that makes sense so I guess we can close this then? Sorry again for the delayed response.

**Pull request closed without merging**
